// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAugLo4n0oUDMLIrkyRoeHpYFsflsSpnJE',
    appId: '1:863359606594:web:d44819128c962fb64cb2db',
    messagingSenderId: '863359606594',
    projectId: 'mini-projetexam',
    authDomain: 'mini-projetexam.firebaseapp.com',
    storageBucket: 'mini-projetexam.appspot.com',
    measurementId: 'G-319EQ56QG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIRbImfIO9tEZ0j86Cy6F7LZoJAB8bvo',
    appId: '1:863359606594:android:e3a73401f6a537fb4cb2db',
    messagingSenderId: '863359606594',
    projectId: 'mini-projetexam',
    storageBucket: 'mini-projetexam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyn2LzhUpoCbKHeR4GzdB8fLBZTZXD7I',
    appId: '1:863359606594:ios:446be913289a0ca64cb2db',
    messagingSenderId: '863359606594',
    projectId: 'mini-projetexam',
    storageBucket: 'mini-projetexam.appspot.com',
    iosClientId: '863359606594-sd6ou7k0j3464p4gc5uolor7o361m7fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.khedma',
  );
}
